### ISSUE TITLE
0 errors though an unexpected exception was thrown

### ISSUE THREAD

**Issue by onetom** [jaycfields/expectations#68] opened 2016-03-18 14:11 UTC
A simple test as `(expect :a (in {:a 1}))` throws an exception as shown below, yet the error count is 0.
Since the documentation doesn't define what counts as an error, so I can't say this case should count as one, but I would expect a clearer message, since it originates from within the test runner.

Environment:
* Clojure 1.8.0
* expectations "2.1.4"
* (System/getProperty "java.version") => "1.8.0_51"

```
> time lein expectations

unexpected error in boot-expectations-test.core-test:5
java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.IllegalArgumentException
        at clojure.lang.RT.seqFrom(RT.java:542)
        at clojure.lang.RT.seq(RT.java:523)
        at clojure.lang.RT.keys(RT.java:599)
        at clojure.core$keys.invokeStatic(core.clj:1510)
        at clojure.core$keys.invoke(core.clj:1506)
        at expectations$eval2307$fn__2308.invoke(expectations.clj:422)
        at clojure.lang.MultiFn.invoke(MultiFn.java:243)
        at boot_expectations_test.core_test$expect1111643923$fn__2585.invoke(core_test.clj:5)
        at boot_expectations_test.core_test$expect1111643923.invokeStatic(core_test.clj:5)
        at boot_expectations_test.core_test$expect1111643923.invoke(core_test.clj:5)
        at expectations$test_var$fn__2064.invoke(expectations.clj:229)
        at expectations$test_var.invokeStatic(expectations.clj:225)
        at expectations$test_var.invoke(expectations.clj:219)
        at expectations$test_vars$fn__2099.invoke(expectations.clj:263)
        at expectations$create_context.invokeStatic(expectations.clj:243)
        at expectations$create_context.invoke(expectations.clj:241)
        at expectations$test_vars.invokeStatic(expectations.clj:263)
        at expectations$test_vars.invoke(expectations.clj:249)
        at expectations$run_tests.invokeStatic(expectations.clj:308)
        at expectations$run_tests.invoke(expectations.clj:301)
        at expectations$run_all_tests.invokeStatic(expectations.clj:314)
        at expectations$run_all_tests.invoke(expectations.clj:313)
        at user$eval2590.invokeStatic(form-init5919810096266834654.clj:1)
        at user$eval2590.invoke(form-init5919810096266834654.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
nil

Ran 1 tests containing 0 assertions in 18 msecs
0 failures, 0 errors.
        9.27 real        23.22 user         1.09 sys
```

**Comment by seancorfield** [comment] 2016-07-07 19:44
When the test is invalid in a way that prevents it from running the actual expression, it's not an "error" in your expression-under-test, and there's not much context to trace back to. Changing the error message here:

https://github.com/jaycfields/expectations/blob/master/src/cljc/expectations.cljc#L232

so that it explains the exception was most likely caused by a badly written test is probably about the best that can be done here?

**Comment by jaycfields** [comment] 2016-07-07 22:30
yeah, I can't think of a better solution either. I'm going to close this for now, but I'm happy to reopen if someone has a better idea.

**Closed by jaycfields** 2016-07-07 22:30 UTC
